name: Deploy staging

on:
  push:
    branches: develop
  pull_request:
    types: [opened, synchronize]

jobs:
  build-js:
    name: Build js + css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn build
        run: |
          yarn install
          yarn prod
          cat public/mix-manifest.json
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
  test-php:
    name: Test/lint php
    runs-on: ubuntu-latest
    needs: build-js
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 8.0
          extensions: mbstring, bcmath
      - name: Composer install
        run: composer install
      - name: Create mock .env file
        run: cp .env.example .env
      - name: Set application encryption key
        run: php artisan key:generate
      - name: Run tests
        run: ./vendor/bin/phpunit
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [build-js, test-php]
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v1
      - name: Download build assets
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring, bcmath
      - name: Composer install
        run: composer install
      - name: Set up deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          ENVIRONMENT: development
          DOT_ENV: ${{ secrets.DOTENV_DEVELOP_CHARLESHARRIES }}
        run: dep deploy development --tag=${{ env.GITHUB_REF }} -vvv
