name: Deploy staging

on:
  push:
    branches: develop
  pull_request:
    types: [opened, synchronize]

jobs:
  build-js:
    name: Build js + css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn build
        run: |
          yarn install
          yarn prod
          cat public/mix-manifest.json
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
  test-php:
    name: Test/lint php
    runs-on: ubuntu-latest
    needs: build-js
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, bcmath
      - name: Composer install
        run: composer install
      - name: Create mock .env file
        run: cp .env.example .env
      - name: Set application encryption key
        run: php artisan key:generate
      - name: Run tests
        run: ./vendor/bin/phpunit
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-js, test-php]
    if: github.ref == 'refs/heads/develop'
    steps:
    - name: SSH into labs and `git pull`
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: cd ${{ secrets.DIRECTORY }} && git pull origin main && composer install && npm run build
